In [2]:
import tensorflow as tf
import numpy as np

In [4]:
test_lens = [2, 2, 3, 1, 1]
test_offrs = (
    [
        [
            [1, 2, 3, 4], [5, 6, 7, 8], [0, 0, 0, 0]
        ],
        [
            [19, 11, 45, 76], [120, 42, 19, 19], [0, 0, 0, 0]
        ],
        [
            [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]
        ],
        [
            [20, 22, 21, 24], [0, 0, 0, 0], [0, 0, 0, 0]
        ],
        [
            [2, 2, 2, 2], [0, 0, 0, 0], [0, 0, 0, 0]
        ]
    ])
test_labels = (
[
    [1, 2, 0],
    [4, 5, 0],
    [9, 9, 10],
    [1, 0, 0],
    [4, 0, 0]
])

In [5]:
test_lens = np.array(test_lens)
test_offrs = np.array(test_offrs)
test_labels = np.array(test_labels)

In [6]:
test_offrs.shape

(5, 3, 4)

In [7]:
offrs = tf.placeholder(test_offrs.dtype, test_offrs.shape)
lens = tf.placeholder(test_lens.dtype, test_lens.shape)
lables = tf.placeholder(test_labels.dtype, test_labels.shape)

In [8]:
features_dict = {}
features_dict['offrs'] = offrs
features_dict['lens'] = lens

In [9]:
dataset = tf.data.Dataset.from_tensor_slices((features_dict, lables))

In [10]:
dataset = dataset.repeat()
dataset = dataset.batch(32)

In [11]:
iterator = dataset.make_initializable_iterator()


In [18]:
sess = tf.Session()
sess.run(iterator.initializer, feed_dict={lens: test_lens,
                                         offrs: test_offrs,
                                         lables: test_labels})
data, curr_labels = sess.run(next_el)
curr_offrs = data['offrs']
curr_lens = data['lens']
sess.close()
print(curr_offrs)
print(curr_lens)
print(curr_labels)

[[[  1   2   3   4]
  [  5   6   7   8]
  [  0   0   0   0]]

 [[ 19  11  45  76]
  [120  42  19  19]
  [  0   0   0   0]]

 [[  1   2   3   4]
  [  5   6   7   8]
  [  9  10  11  12]]

 [[ 20  22  21  24]
  [  0   0   0   0]
  [  0   0   0   0]]

 [[  2   2   2   2]
  [  0   0   0   0]
  [  0   0   0   0]]

 [[  1   2   3   4]
  [  5   6   7   8]
  [  0   0   0   0]]

 [[ 19  11  45  76]
  [120  42  19  19]
  [  0   0   0   0]]

 [[  1   2   3   4]
  [  5   6   7   8]
  [  9  10  11  12]]

 [[ 20  22  21  24]
  [  0   0   0   0]
  [  0   0   0   0]]

 [[  2   2   2   2]
  [  0   0   0   0]
  [  0   0   0   0]]

 [[  1   2   3   4]
  [  5   6   7   8]
  [  0   0   0   0]]

 [[ 19  11  45  76]
  [120  42  19  19]
  [  0   0   0   0]]

 [[  1   2   3   4]
  [  5   6   7   8]
  [  9  10  11  12]]

 [[ 20  22  21  24]
  [  0   0   0   0]
  [  0   0   0   0]]

 [[  2   2   2   2]
  [  0   0   0   0]
  [  0   0   0   0]]

 [[  1   2   3   4]
  [  5   6   7   8]
  [  0   0   0   0]]

 [[ 19  

In [15]:
next_el = iterator.get_next()

RuntimeError: Attempted to use a closed Session.

In [16]:
sess = tf.Session(

FailedPreconditionError: GetNext() failed because the iterator has not been initialized. Ensure that you have run the initializer operation for this iterator before getting the next element.
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?], [?,3,4], [?,3]], output_types=[DT_INT64, DT_INT64, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]

Caused by op 'IteratorGetNext', defined at:
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/opim/eplu/.virtualenvs/jupyterlab-py36/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/opim/eplu/.virtualenvs/jupyterlab-py36/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/opim/eplu/.virtualenvs/jupyterlab-py36/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 486, in start
    self.io_loop.start()
  File "/home/opim/eplu/.virtualenvs/jupyterlab-py36/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/asyncio/base_events.py", line 1426, in _run_once
    handle._run()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "/home/opim/eplu/.virtualenvs/jupyterlab-py36/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 117, in _handle_events
    handler_func(fileobj, events)
  File "/home/opim/eplu/.virtualenvs/jupyterlab-py36/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/opim/eplu/.virtualenvs/jupyterlab-py36/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/home/opim/eplu/.virtualenvs/jupyterlab-py36/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/opim/eplu/.virtualenvs/jupyterlab-py36/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/home/opim/eplu/.virtualenvs/jupyterlab-py36/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/opim/eplu/.virtualenvs/jupyterlab-py36/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/opim/eplu/.virtualenvs/jupyterlab-py36/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/opim/eplu/.virtualenvs/jupyterlab-py36/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/home/opim/eplu/.virtualenvs/jupyterlab-py36/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/opim/eplu/.virtualenvs/jupyterlab-py36/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/opim/eplu/.virtualenvs/jupyterlab-py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/home/opim/eplu/.virtualenvs/jupyterlab-py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/opim/eplu/.virtualenvs/jupyterlab-py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2903, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/opim/eplu/.virtualenvs/jupyterlab-py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-15-e4494eb7596d>", line 1, in <module>
    next_el = iterator.get_next()
  File "/home/opim/eplu/.virtualenvs/jupyterlab-py36/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 370, in get_next
    name=name)), self._output_types,
  File "/home/opim/eplu/.virtualenvs/jupyterlab-py36/lib/python3.6/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 1466, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/home/opim/eplu/.virtualenvs/jupyterlab-py36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/opim/eplu/.virtualenvs/jupyterlab-py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/opim/eplu/.virtualenvs/jupyterlab-py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

FailedPreconditionError (see above for traceback): GetNext() failed because the iterator has not been initialized. Ensure that you have run the initializer operation for this iterator before getting the next element.
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?], [?,3,4], [?,3]], output_types=[DT_INT64, DT_INT64, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]
